image: Ubuntu

install:
- pushd /usr/local && curl -L https://dl.dagger.io/dagger/install.sh | sudo sh && dagger version && popd

test_script:
- dagger project init
- dagger project update
- dagger do load --log-format plain

build: off
