image: Ubuntu

build: off
install:
- pushd /usr/local && curl -L https://dl.dagger.io/dagger/install.sh | sudo sh && popd

test_script:
- dagger version
- dagger project init
- dagger project update
- dagger do load --log-format plain
- docker images
